### ISSUE TITLE
[Enhancement Request] Add space support in value names for patches

### ISSUE THREAD

**Issue by Electrocutor** [sarbian/ModuleManager#107]
Example:
			%GAMEOBJECTS {
				%Squad/Parts/Command/mk1pod/model(Clone) = false
				%VenStockRevamp/Part Bin/NewParts/Mk2pod/MK2pod(Clone) = true
			}

**Comment by blowfishpro** [comment]
I don't think this would conflict with anything, @sarbian do you see any potential problems?

**Comment by sarbian** [comment]
No, I don't see any issue
