### ISSUE TITLE
More clarification on NEEDS parameters

### ISSUE THREAD

**Issue by Gfurst** [sarbian/ModuleManager#112]
Something that ins't very clear to me, I tried some methods of `NEEDS` combining, for exemple:

```
:NEEDS[!RealFuels|!TacLifeSupport]:
:NEEDS[kOS]:NEEDS[RemoteTech]:
:NEEDS[DMagicOrbitalScience&UniversalStorage]:
```

both seem to apply correctly, but I'm unsure as to which to use, and which filter operators apply in this case `*?@!#~`, since they are not the same thing as a part nodes or keys. Beyond me just wondering about it, I think the wiki could use more documentation over this topic.

**Comment by blowfishpro** [comment]
More than one `:NEEDS` block definitely does not work.

**Comment by Gfurst** [comment]
I disagree `:NEEDS[DMagicOrbitalScience]:NEEDS[UniversalStorage]` definitely does work, though I'm not sure if it just checks the first or the latter.

What about `NEEDS[....&|....]`, `&` or `|`, would that be the proper way?

**Comment by Gfurst** [comment]
Cheers, thanks for the explanation, I think it would benefit to make this behavior more explicit in the docs.

**Comment by Gfurst** [comment]
Just saw there is a bit of documentation about this on syntax wiki page.
