### ISSUE TITLE
#35 - x patches applied, found <color=yellow>y warnings</yellow>

### ISSUE THREAD

**Issue by Gordon-Dry** [sarbian/ModuleManager#125]
I guess it should be
`<color=yellow>8 warnings</color>`
;)

**Comment by Gordon-Dry** [comment]
Btw that version only shows me x errors in the result, but I have no chance to find which patches are the culprit - it's not listed as it's with the 3.0.7 rls.

**Comment by blowfishpro** [comment]
Sorry, what's the issue here?  I'm not seeing anything obvious.  And this is on the dev branch?

**Comment by blowfishpro** [comment]
Got another report on the forum, makes sense now
