### ISSUE TITLE
Missing files??

### ISSUE THREAD

**Issue by KiritoandAsuna** [sarbian/ModuleManager#152]
Yo just tried to install on linux mint 19.2 using the makefile and it was saying that its missing a folder called properties, and a file called resources.resx and i cant seem to find it anywhere

**Comment by blowfishpro** [comment]
I have no idea how the makefile is supposed to work but you shouldn't need it if you just want to install, the compiled dll will work across platforms

**Comment by KiritoandAsuna** [comment]
okay, well i cant seem to find to find the .dll files, and im not entirely sure how to use them as an installation method

**Comment by blowfishpro** [comment]
Downloads and how to install are both in the first post of the ModuleManager thread on the KSP forums
