### ISSUE TITLE
Detecting KSP version

### ISSUE THREAD

**Issue by Sigma88** [sarbian/ModuleManager#154]
I was recently asked if it was possible to apply conditional patches depending on which version of ksp is being run.

I don't think it is, but I think this could be a nice addition to ksp.

One possible approach that came to mind is hardcoding into mm the addition of a special mod, that could be called something like `KSPv1.9.0`
Where the version number is read directly from the plugin.

This would allow users to write patches with `:NEEDS[KSPv1.9.0]` to make sure they only run when a specific version of ksp is used.

There are other approahes of course, but this seems simple enough

**Comment by blowfishpro** [comment]
Is this different than #116 ?

**Comment by Sigma88** [comment]
Nope. I had checked briefly but did not see that issue. Sorry for the duplicate
