### ISSUE TITLE
Create-or-replace semantics with nodes that don't have a name

### ISSUE THREAD

**Issue by Starstrider42** [sarbian/ModuleManager#16]
This is a follow-up to Majiir/Kethane#263. I'm interested in writing MM patches for parts that use the Kethane modules, which are identified by the (hopefully) unique identifier `Name`, rather than the conventional `name`. I've been running into the problem that create-or-replace syntax doesn't work if you can't identify a node by `name`. Something like

```
%NODE[*]:HAS[#Name[Foo]]
```

doesn't work by design because of uniqueness issues. As @Majiir pointed out, the same problem can occur with other parts of the KSP config space, such as testing for the presence of an `EXPERIMENT_DEFINITION` (where `id` appears to be a unique key).

**Comment by blowfishpro** [comment]
`%EXPERIMENT_DEFINITION:HAS[#id[blah]]` definitely works now.  Can this be closed?

**Comment by Starstrider42** [comment]
I think so.
