### ISSUE TITLE
ModuleManager.log filepath

### ISSUE THREAD

**Issue by Aquilux** [sarbian/ModuleManager#164]
Upon loading and seeing some warnings and errors generated by MM, I decided to see if I could find the log output for those errors. But unfortunately the directory in which the log file should have been did not exist. When reviewing the log entry containing the directory I found this:
`[LOG 14:56:04.362] [ModuleManager] Patching started on a new thread, all output will be directed to C:/Kerbal Space Program/ksp 1.10.1 moded/KSP_x64_Data/../Logs\ModuleManager\ModuleManager.log`

The log file appears as though it is not being generated due to the use of backslashes instead of forward slashes in the file path.

**Comment by Aquilux** [comment]
![MMissue4](https://user-images.githubusercontent.com/1621589/94377248-be421280-00d4-11eb-8e94-f01eb18ac0eb.PNG)
![MMissue3](https://user-images.githubusercontent.com/1621589/94377249-bedaa900-00d4-11eb-9173-d5478998b7bc.PNG)
![MMissue2](https://user-images.githubusercontent.com/1621589/94377250-bedaa900-00d4-11eb-99ce-a4c97a1bf66e.PNG)
![MMissue1](https://user-images.githubusercontent.com/1621589/94377252-bedaa900-00d4-11eb-9e80-c82ee170ba21.PNG)

**Comment by Aquilux** [comment]
![MMissue1](https://user-images.githubusercontent.com/1621589/94377285-137e2400-00d5-11eb-88dd-fd0d6e1c685c.PNG)
![MMissue2](https://user-images.githubusercontent.com/1621589/94377283-12e58d80-00d5-11eb-90b0-581f5daea373.PNG)
![MMissue3](https://user-images.githubusercontent.com/1621589/94377281-12e58d80-00d5-11eb-912b-4015abd7ab9b.PNG)
![MMissue4](https://user-images.githubusercontent.com/1621589/94377280-124cf700-00d5-11eb-8b72-322eef9a7f6f.PNG)

**Comment by sarbian** [comment]
Unity does not differentiate between backward and forward slash.
The only place you did not share a screenshot of is where the KSP exe is, which is also where the log should be.

**Comment by Aquilux** [comment]
My apologies. I thought the log file should be in the directory that module manager indicated in the main KSP log. On re-inspection I have found the module manager log in the main KSP log, though there is no "ModuleManager.log" file in my KSP dir.

![MMissue5](https://user-images.githubusercontent.com/1621589/94513196-eadc5400-01d2-11eb-940d-f0990e6273f5.PNG)

**Comment by blowfishpro** [comment]
`ModuleManager.log` exists in `<ksp_root>/Logs/ModuleManager/`.  Its contents are also copied to the main log for convienience.

**Comment by Aquilux** [comment]
Ah, my apologies then. I was just confused as that is not the path stated near the beginning of the main KSP log. I was expecting
`C:/Kerbal Space Program/ksp 1.10.1 moded/KSP_x64_Data/. . . /Logs/ModuleManager/ModuleManager.log`
as indicated in the main log, not 
`C:/Kerbal Space Program/ksp 1.10.1 moded/Logs/ModuleManager/ModuleManager.log`

As the file is generated my major concern is alleviated, but the filepath for the log as indicated in the main KSP log still does not match it's actual location and while this is a low level concern, it should probably be fixed eventually to prevent future confusion.

**Comment by blowfishpro** [comment]
The path is valid and correct - `..` in a path means going up a level.  But it is confusing and difficult to read.  Thank KSP for generating its own root path this way and not normalizing it.  Maybe ModuleManager can normalize the path.

**Comment by Aquilux** [comment]
Oh... That's ..... odd. The way I was reading that was it cutting excessive length out of the file path. I don't think I've ever seen that particular notation in an informative note before.
