### ISSUE TITLE
Mind Control & open world pvp & Guards

### ISSUE THREAD

**Issue by miki-g** [sarbian/ModuleManager#174]
Mind control in pvp zones bug guards, they kill controlled player instead of priest, then also kill priest
but killing ( inactive / passive ) controled player by guards is bug

& shadow priest Funnin needs some /slap-s for using this bug on Isle of Quel'Danas

thanks

**Comment by sarbian** [comment]
I assume you are talking about some private WoW server. Which has nothing to do with this project.

**Comment by miki-g** [comment]
aaargh, missclick :D ... we need more kerbal multiplayer to avoid wow brainwasher :D
