### ISSUE TITLE
KSP stuck on loading applying module manager patches

### ISSUE THREAD

**Issue by ZilgornZeypher** [sarbian/ModuleManager#25]
While loading KSP when it says loading Module manager patches it gets stuck at the part FS nose engine electric and just sits there. If I remove Firespitter it loads I've tried deleteing the module manager cache and reinstalling it.

From KSP log
'Firespitter/Parts/Engine/FS_noseEngineElectric/part/FSnoseEngineElectric'
[ERR 17:44:23.819] [ShipTemplate]: No Resource definition found for RESOURCE

[LOG 17:44:23.822] FSCoolant not found in resource database. Propellant Setup has failed.
[EXC 17:44:23.824] NullReferenceException: Object reference not set to an instance of an object
	ModuleEngines.SetupPropellant ()
	ModuleEngines.OnLoad (.ConfigNode node)
	PartModule.Load (.ConfigNode node)
	Part.AddModule (.ConfigNode node)
	PartLoader.ParsePart (.UrlConfig urlConfig, .ConfigNode node)
	PartLoader+.MoveNext ()
[EXC 17:44:23.827] NullReferenceException: Object reference not set to an instance of an object
	Firespitter.engine.FSengineSounds.createGroup (.FXGroup group, System.String name, Boolean loop)
	Firespitter.engine.FSengineSounds.OnStart (StartState state)
	Part.ModulesOnStart ()
	Part+.MoveNext ()
[LOG 17:44:41.074] RemoteTech: ModuleRTAntennaPassive: OnDestroy

**Comment by jakkarth** [comment]
This is not a bug in Module Manager. It means you're either using an outdated version of Firespitter, or you've installed it incorrectly. The definition for the FSCoolant resource should be in GameData/Firespitter/Resources/Firespitter.cfg.
