### ISSUE TITLE
Can't seem to make this work - RESULTS

### ISSUE THREAD

**Issue by NathanKell** [sarbian/ModuleManager#29]
@sarbian  Trying to nuke existing RESULTS in experiments.
I've tried [this](https://github.com/KSP-RO/RP-0/blob/ac45a8c2d18ed7c3a7c6d555003c72888689e62a/GameData/RP-0/Science/ScienceReports.cfg) after [this old version](https://github.com/KSP-RO/RP-0/blob/e604525aa423bcfcf7fc8ad723d765ff935ba045/GameData/RP-0/Science/ScienceReports.cfg) didn't work. Neither works, although other things on BEFORE[RP-0] do run, and I get no MM errors.
(there area  couple MM errors from another patch, but they're caught.)

Any ideas? :\

**Comment by sarbian** [comment]
experimentID => id ?

**Comment by NathanKell** [comment]
Yep. Will try that. 4am head.

Though that was only done because the prior version didn't work--does ,* not work for toplevel nodes?

**Comment by sarbian** [comment]
Yep ",*" does not work for top node and MM always apply patch on all top nodes. So : 
@EXPERIMENT_DEFINITION:BEFORE[RP-0]  should work fine

**Comment by Olympic1** [comment]
I always use @EXPERIMENT_DEFINITION[*]:HAS[#id[xx]] (xx = id)
and it works fine
