### ISSUE TITLE
Hidden folder support on Linux

### ISSUE THREAD

**Issue by Garoe** [sarbian/ModuleManager#36]
On ubuntu the default folder for steam games is  ~/.local/share/Steam/steamapps/common
The dialogue for selecting the location of KSP does not show any hidden folders, at least having the option to input the folder path manually would fix it. As a workaround I had to create a link.

**Comment by sarbian** [comment]
"The dialogue for selecting the location of KSP"? What are you talking about? There is no UI in Modulemanager

**Comment by Garoe** [comment]
I am terribly sorry, I thought this repository was for the Mod Admin tool, I feel like an idiot.
