### ISSUE TITLE
delete issues in 2.6.15

### ISSUE THREAD

**Issue by Sigma88** [sarbian/ModuleManager#39]
there's an issue in 2.6.15 with the delete (!) command for keys.

how to reproduce:

```
//// CFG /////////////////

TESTNODE
{
	testkey = 0
	testkey = 1
	testkey = 2
	testkey = 3
}
@TESTNODE
{
	!testkey,* = DEL
}
//////////////////////////


// RESULT ////////////////

UrlConfig
{
	name = TESTNODE
	type = TESTNODE
	parentUrl = /test
	url = /test/TESTNODE
	TESTNODE
	{
		testkey = 1
		testkey = 2
		testkey = 3
	}
}

//////////////////////////
```

!testkey,* = DEL

should delete all "testkey"s but deletes only the first one instead

I guess this is not intended, maybe it has something to do with the patch @ThomasKerman added for issue #37

**Comment by ThomasKerman** [comment]
Hmm, I only added the ,* stuff to edit and copy, totally missed the delete thing. 

Seems to be fairly easy, I can make a new PR to fix it.

**Comment by sarbian** [comment]
Please do, I am in the middle of a full PC re install here :)

**Comment by sarbian** [comment]
And I merged the fix, thanks. 2.6.16 is available
