### ISSUE TITLE
MM gets stuck in load screen.

### ISSUE THREAD

**Issue by RealKolago** [sarbian/ModuleManager#45]
If MM loads (not from cache) and works on the cfg files it's getting stuck and only continuous to load when I click into the KSP screen. I run KSP with the options -popupwindow and -force-opengl.
This happens only if I change to my to my second screen and doing something there like reading emails and so on.

No errors in the log related to this.

**Comment by sarbian** [comment]
I will need the log anyway

**Comment by RealKolago** [comment]
Here is the log: https://www.dropbox.com/s/5kcrj02i92a4s5g/output_log10.zip?dl=0

**Comment by RealKolago** [comment]
This is gone in Kerbal 1.1.2 and latest MM.
