### ISSUE TITLE
White space errors message not readable. 

### ISSUE THREAD

**Issue by mellester** [sarbian/ModuleManager#46]
A edit will Generate a error if there is a space in the wrong place
```
@PART[DERP_FuelCan | DERP_InlineTank] {...} 
```

compared to 
```
@PART[DERP_FuelCan|DERP_InlineTank] {...} 
```

This error is very hard to find in the ksp logs.

**Comment by sarbian** [comment]
The problem is that MM does not even see the space. The line was cut when KSP loaded the cfg.
I am not sure I can do much :(

**Comment by mellester** [comment]
Thx for the reply. keep up the good work.
