### ISSUE TITLE
Spaces in Part name

### ISSUE THREAD

**Issue by schnip** [sarbian/ModuleManager#48]
Is there any way to properly deal with spaces in a part name while making a config? I am currently just putting a \* where the space should go, but I would like to use a more eloquent solution if it is available.

**Comment by anxcon** [comment]
a ? also works, ? is single char wildcard, * is multi char wildcard

**Comment by schnip** [comment]
Cool! I wasn't sure if that one would work in here since it was not mentioned anywhere I could find in the documentation.
