### ISSUE TITLE
1.1 and Kopernicus

### ISSUE THREAD

**Issue by swavkulinski** [sarbian/ModuleManager#49]
looks like dies on reflection when loading Kopernicus.

My rig is linux, running ksp 64bit (don't be misled by log saying x86, it is a link to x86_64). happens on 2.6.18 and 21

https://gist.github.com/swavkulinski/a0536426d41fe01e2f3022350f267c50

**Comment by sarbian** [comment]
There is no Kopernicus version build for 1.1. This is why it does that....
