### ISSUE TITLE
deleting .dll files and MM cache

### ISSUE THREAD

**Issue by Sigma88** [sarbian/ModuleManager#50]
when deleting a dll from gamedata all the patches that uses :NEEDS[thatDLLname] should not get loaded, however, if the cache is generated with the DLL in place, then the DLL gets removed, MM will still load the old cache instead of generating a new one, leading to weird issues

**Comment by sarbian** [comment]
This will be fixed in the next release. Thanks

**Comment by Sigma88** [comment]
thanks to you! :+1:
