### ISSUE TITLE
! Not deleting in .21

### ISSUE THREAD

**Issue by TedThompson** [sarbian/ModuleManager#51]
In a cfg I have

`!mesh`

Which used to remove "mesh=model".  However when I check the database in game, the mesh=model key remains in ksp1.1.  The various additions my cfg makes to the part in question appear as expected.

Among them is a MODEL{...} node of course.

**Comment by Kerbas-ad-astra** [comment]
A line like that is considered invalid by KSP's ConfigNode loader and will be eaten by KSP before MM even sees it.  A line must contain an equals sign (with content on both sides of it) to be valid, so you need to have something like "!mesh = delete".

**Comment by TedThompson** [comment]
So, the proper syntax is 
!keynote = doesnt_matter_what_is_here_but_you_need_something

Correct?

**Comment by TedThompson** [comment]
No edit.  key =, not keynote =

 (stupid phone)

**Comment by sarbian** [comment]
it is. Closing now :)
