### ISSUE TITLE
type-less nodes break mm

### ISSUE THREAD

**Issue by Sigma88** [sarbian/ModuleManager#54]
I know this is not a mm bug per se, and it's just the result of bad cfg from modders.

but I have received a decent number of bug reports that were related to this issue, so I would like to know if a simple solution could be found in mm.

**THE ISSUE**

these are a couple of examples of code that break mm

```
ROOTNODE
{
    SUBNODE
    {
        stuff = optional

        {
        }
    }
}
```

```
ROOTNODE
{
    SUBNODE
    {
        stuff = optional
        //DUMBNODE
        {
        }
    }
}
```

would it be possible to tell mm to just delete those "nodes" which do not have a type defined (either because it was commented out or because it was never defined) so that bad configs are less an issue than they are now?

thanks :)

**Comment by Sigma88** [comment]
[for reference](http://forum.kerbalspaceprogram.com/index.php?/topic/139245-113-kopernicus-kumars-dwarf-stars-v02-26jun16/&do=findComment&comment=2675629)

**Comment by blowfishpro** [comment]
This should probably be handled, but it doesn't feel right to me to just ignore these nodes - maybe it should alert the user that there is an error in that config?

**Comment by Sigma88** [comment]
*****iirc*****, the bug also appears if by mistake an empty line creeps in between node type and node brackets:

```
NODE

{
    key = whatever
}
```

**Comment by blowfishpro** [comment]
It does, because KSP parsed that as a nameless node.

**Comment by Sigma88** [comment]
yes, I was just giving context on what could cause the bug :)

other than the usual *``MOD_IT_TILL_IT_BREAKS``* attitude

**Comment by Sigma88** [comment]
this is from the old mm, I haven't checked it in the new version so I am going to close it for now untill I have an idea on how this works now
