### ISSUE TITLE
Possible problem with long parameters for NEEDS.

### ISSUE THREAD

**Issue by Galenmacil** [sarbian/ModuleManager#58]
After seeing several patches getting applied even though their NEEDS is not met, I have come to the following conclusion:

Long parameters are not processed correctly by NEEDS. 

Prime example of this, verifiable on several mod that use similar syntax:

_@PART[aeroPartxx]:NEEDS[FerramAerospaceResearch]:BEFORE[FerramAerospaceResearch]
{
    @minimum_drag = 0
    @maximum_drag = 0
    @angularDrag = 0
    !MODULE[ModuleLiftingSurface] {}
}_

Even though FerramAerospaceResearch IS NOT available, the patch still gets applied.

**Comment by sarbian** [comment]
This runs perfectly fine here.
"[ModuleManager] Deleting Node in file /test subnode: @PART[aeroPartxx]:NEEDS[FerramAerospaceResearch]:BEFORE[FerramAerospaceResearch] as it can't satisfy its NEEDS"

Since you do not provide a full log I can not identify your actual problem.
