### ISSUE TITLE
Possible problem with long parameters for NEEDS.

### ISSUE THREAD

**Issue by Galenmacil** [sarbian/ModuleManager#59]
OK Sarbian, sorry for last time let's try this again with a log file this time:

Using the same example as the last time, check my log at line 10199. The patch is applied even though FAR is not present. That particular patch is:

_@PART[quizTechMk1K10Cockpit]:NEEDS[FerramAerospaceResearch]:BEFORE[FerramAerospaceResearch]
{
    @minimum_drag = 0
    @maximum_drag = 0
    @angularDrag = 0
    !MODULE[ModuleLiftingSurface] {}
}_

Cannot attach the ZIP file here for some reason, here is a link to it:

http://www.mediafire.com/file/j80570uq9sx9h1e/LOG.zip

**Comment by sarbian** [comment]
From the log:

LOG 17:51:12.988] Config(@PART[quizTechVTOLwing]:NEEDS[FerramAerospaceResearch]:FOR[FerramAerospaceResearch]) QuizTechAeroContinued/MM_Patches/quizTech_aero_FAR/@PART[quizTechVTOLwing]:NEEDS[FerramAerospaceResearch]:FOR[FerramAerospaceResearch]

That patch use a FOR[FerramAerospaceResearch]. It means that this patch declare FerramAerospaceResearch is installed.

That mod (QuizTechAeroContinued) uses a bad MM patch. That s the source of your problem.
