### ISSUE TITLE
Target All keys bug

### ISSUE THREAD

**Issue by Sigma88** [sarbian/ModuleManager#61]
using the feature FindAndReplace is now failing to apply when targetting all keys with ,*

Steps to reproduce:
1- clean install of KSP 1.2.1
2- MM 2.7.2
3- following custom config
```
TEST
{
	key = 1 2 3 4
	key = 4 5 6 7
	key = 7 8 9 0
	key = 10 11
}
@TEST
{
	@key ^= :$:x:
	@key,* ^= :$:y:
	@key,1 ^= :$:z:
	@key,* ^= :4:w:
	@key,2 ^= :7:k:
}
```

this is what the cache contains at the end:

```
UrlConfig
{
	name = TEST
	type = TEST
	parentUrl = /TEST
	url = /TEST/TEST
	TEST
	{
		key = 1 2 3 4x
		key = 4 5 6 7z
		key = k 8 9 0
		key = 10 11
	}
}
```

as you can see the only missing letters are  **y** and **w** which are both supposed to be applied to all keys by using ,*

find attached logs and other relevant files
(I've added .txt at the end, because github)

[output_log.txt](https://github.com/sarbian/ModuleManager/files/572888/output_log.txt)
[ModuleManager.ConfigCache.txt](https://github.com/sarbian/ModuleManager/files/572890/ModuleManager.ConfigCache.txt)
[TEST.cfg.txt](https://github.com/sarbian/ModuleManager/files/572891/TEST.cfg.txt)

**Comment by Sigma88** [comment]
on a further inspection it seems like the bug is present also for sum and multiplication

```
TEST
{
	key = 1
	key = 4
	key = 7
	key = 10
}
@TEST
{
	@key,* += 2
	@key,* *= 2
}
```

the cache file using this cfg shows the same numbers defined in the first node, the patch does nothing at all

**Comment by Sigma88** [comment]
**UPDATE Nr2**

It seems that using MM 2.7.0 solves this issue

**Comment by sarbian** [comment]
It was the regex changes, I forgot that case... 
It should be ok in 2.7.3
