### ISSUE TITLE
Feature Request: Flags (and not the type you fly)

### ISSUE THREAD

**Issue by Ruedii** [sarbian/ModuleManager#62]
Is there a way we can get flag indicators.  These are basically strings that would indicate either user preferences or the existence of mods.

For instance:
`$FuelSwitch=Firespitter` could be used to set to use Firespitter fuelswitch to switch fuels.
and 
`$FuelSwitch=Intersteller` could be used to set to use Intersteller fuelswitch instead.

Likewise these two could be detected with 
`@if $FuelSwitch=Firespitter { . . . }`
and
`@if $FuelSwitch=Intersteller { . . . }`

Likewise:
$Firespitter could indicate that Firespitter was installed AND should be used for mods that it is not mandatory for, without using problematic autodetection methods.  By default it would be filled with a default value non-null value to indicate that the variable exists, because this type of flag would be searched for.

This would make life a lot easier for mod makers, who could best utilize the system provided to them.

**Comment by Kerbas-ad-astra** [comment]
The "NEEDS[X]" flag does exactly this.  "NEEDS[Firespitter]" (or [!Firespitter]") etc.

**Comment by Ruedii** [comment]
this should have a provides[X] function added.


On Nov 5, 2016 8:16 PM, "Kerbas-ad-astra" <notifications@github.com> wrote:

The "NEEDS[X]" flag does exactly this. "NEEDS[Firespitter]" (or
[!Firespitter]") etc.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sarbian/ModuleManager/issues/62#issuecomment-258651275>,
or mute the thread

**Comment by sarbian** [comment]
You mean like FOR[xxx] ?
