### ISSUE TITLE
Localization Modding

### ISSUE THREAD

**Issue by Olympic1** [sarbian/ModuleManager#68]
I'm working on localization for Dutch (later French and German), but in order to get it to work you need to edit the `settings.cfg` and `buildID.txt` files. Would it be possible to edit both files using MM?

**Comment by Olympic1** [comment]
You can change the language in the `settings.cfg` but not in de the `buildID.txt`. Could it be possible to do this?

**Comment by sarbian** [comment]
Is the content of the buildID.txt used in any what that impact localisation in 1.3 ?

**Comment by Olympic1** [comment]
Yes, if you only change the language in the settings to ex. nl-nl but leave the language in the buildID on en-us, you will get this: http://i65.tinypic.com/212wx0o.png

**Comment by sarbian** [comment]
Ok, I had a look at how it works and this whole loc things is really getting on my nerve.

The game loads the buildID file each time it needs to get the info. I have no way of overloading the result and I will not change the content of a stock file from MM.

So try to complain to the dev.

**Comment by Olympic1** [comment]
Ok, no problem. Thanks for trying.

**Comment by Olympic1** [comment]
I found a way to change the language using a plugin. Making a `ConfigNode` and reading the language from it, makes it possible to call `KSP.Localization.Localization.instance.SwitchToLanguage(language);` to change the language. Also this way it supports MM too.
